### PR TITLE
Kanren

### LINKED ISSUE #15: Name Change to `kanren`
The LogPy name conflicts with a logging library.  In particular there is a conflict in the `pypi` registry.  The LogPy organization is also growing to support more projects. 

I'm considering changing the name of this project to `kanren`

### PR DESCRIPTION
**Pull request by lucaswiman**
Switches the name to `kanren`. Fixes #15.

### CODE REVIEW

**Comment by lucaswiman** [comment]
This has been deployed to pypi: https://pypi.python.org/pypi/kanren

**Comment by lucaswiman** [comment]
New version with a deprecation notice uploaded to the `logic` package: https://pypi.python.org/pypi/logic/

**Comment by lucaswiman** [comment]
🍏 build and I verified I can `pip install kanren` and run the corleone example. cc @t3db0t

**Comment by t3db0t** [comment]
Nice! Thanks all!

**Comment by t3db0t** [comment]
I verified with one test, but my example at https://github.com/t3db0t/logpy-examples/blob/master/logpyZebra.py (change not pushed) fails with:

```
$ python logpyZebra.py 
Traceback (most recent call last):
  File "logpyZebra.py", line 58, in <module>
    (membero,	(var(), var(), var(), 'zebra', var()), houses)
  File "/Library/Python/2.7/site-packages/kanren/core.py", line 53, in lall
    return (lallgreedy, ) + tuple(earlyorder(*goals))
  File "/Library/Python/2.7/site-packages/kanren/core.py", line 155, in earlyorder
    groups = groupby(earlysafe, goals)
  File "/Library/Python/2.7/site-packages/toolz/itertoolz.py", line 93, in groupby
    d[key(item)](item)
  File "/Library/Python/2.7/site-packages/kanren/core.py", line 138, in earlysafe
    goaleval(goal)
  File "/Library/Python/2.7/site-packages/kanren/core.py", line 300, in goaleval
    return find_fixed_point(evalt, goal)
  File "/Library/Python/2.7/site-packages/kanren/core.py", line 285, in find_fixed_point
    cur = f(cur)
  File "/Library/Python/2.7/site-packages/kanren/util.py", line 84, in evalt
    return t[0](*t[1:])
  File "logpyZebra.py", line 9, in lefto
    return membero((q,p), zip(list, list[1:]))
TypeError: 'Var' object has no attribute '__getitem__'
```

Did anything change other than the name?

**Comment by lucaswiman** [comment]
A number of things changed between releases. Try your old code with `logic==0.2.3` to verify the `kanren` name change is not the cause of the issue.

**Comment by t3db0t** [comment]
Just checked; yes, that error occurs with `logic==0.2.3` but had not occurred with whichever version I had before—I didn't look before I changed versions. :o

**Pull request merged**
