### PR TITLE
Testing improvements

### PR DESCRIPTION
**Pull request by skirpichev**
1) Migrating to container-based infrastructure
2) Drop deprecated --use-mirrors option for pip
3) Add more python versions to test

### CODE REVIEW

**Comment by skirpichev** [comment]
@mrocklin, I see coverage call.  Where is the coverage profile?  Shouldn't we add the link to one?

btw, I think this ok to go.

**Comment by mrocklin** [comment]
Sure.  Also, I'm unlikely to collaborate much on this project in the future.  Relying on me for code review is

**Comment by skirpichev** [comment]
> Sure.

Well, it's not clear for me _where_ this coverage profile is.  Sorry for stupid question.

**Comment by skirpichev** [comment]
> Relying on me for code review is probably unwise.

I don't expect answer in general.  Esp., not a quick answer.

**Pull request merged**
