### PR TITLE
Tox coverage

### PR DESCRIPTION
**Pull request by lucaswiman**
@mrocklin @skirpichev This PR makes the following changes:

## API Changes
I renamed some of the `lall` implementations.

Prior to this PR, `lall` was unsafe to use on incorrectly ordered goals (can lead to `EarlyGoalError`), while `lallearly` was safe to use. I renamed `lall` to `lallgreedy`, and made `lallearly` the default `lall`.

This should not cause any change to behavior in cases where goals are correctly ordered, but will cause more conditions to unify correctly. It _is_ a small performance hit, but IMO convenience of the API should trump performance. The old implementation is also available, so if there are performance-critical use cases, `lallgreedy` can be substituted.

AFAICT from searching Google and Github, no one uses `lallearly`, so I don't think there's a need for a compatibility shim.

## Test suite and code coverage
- Use `tox` and `pytest` for running the parameterized test suite locally. I switched the recommended test runner from nose to pytest since pytest seems to be much faster, and has an API that better matches the `assert foo == bar` style that was already present in the test suite.
- 100% statement coverage to the core unification modules. I left some of the `unifymore` module uncovered, since I want to get more experience with using it before I finish the tests there.
- Cleaned up some dead code, fixed some bugs I found with some edge cases, and added the missing `unify_objects_slots`.

### Current coverage report
```
Name                   Stmts   Miss Branch BrPart  Cover   Missing
------------------------------------------------------------------
logpy/__init__.py          8      0      0      0   100%   
logpy/arith.py            34      0      6      0   100%   
logpy/assoccomm.py       116      0     64      1    99%   57->60
logpy/core.py            102      0     38      0   100%   
logpy/dispatch.py          4      0      0      0   100%   
logpy/facts.py            40      0     16      0   100%   
logpy/goals.py            60      0     36      2    98%   78->-46, 81->84
logpy/term.py             25      5      2      1    78%   27-31, 38->40
logpy/unification.py      53      0     24      0   100%   
logpy/unifymore.py        56      5     22      0    94%   187, 191, 195, 199-200
logpy/util.py             75      0     39      0   100%   
logpy/variable.py         33      0      6      0   100%   
------------------------------------------------------------------
TOTAL                    606     10    253      4    98%   
```

### CODE REVIEW

**Comment by lucaswiman** [comment]
@mrocklin: getting `pytest` to work with all the supported versions of Python seems to be a bit of a pain. My general impression is that this library hasn't (yet!) seen a lot of use, so supporting old versions of python seems adding the weight of legacy for no good reason.

Is there a strong argument for continuing to support python 2.6, 3.2 and 3.3? At least dropping support for 2.6 (end of life October, 2013) would simplify things and allow for using nice syntactic sugar like set literals.

**Comment by lucaswiman** [comment]
Alright, I got the build passing dropping just 2.6 and 3.2.

**Comment by mrocklin** [comment]
Sorry for the late response.  I would be fine dropping 2.6 and 3.2.  Generally I have few constraints to impose on this project.

**Comment by mrocklin** [comment]
Merged.  Thanks!

I've also given you commit access to this repository.  Anyone who improves testing infrastructure must clearly by qualified :)

**Pull request merged**
