### PR TITLE
Implement `condp`

### PR DESCRIPTION
**Pull request by brandonwillard**
This PR provides an implementation of [“A Surprisingly Competitive Conditional Operator”](https://www.brinckerhoff.org/scheme2018/papers/Boskin_Ma_Christiansen_Friedman.pdf).

The `condp` operator provides some of the capabilities described in https://github.com/logpy/logpy/issues/3.

### CODE REVIEW

**Comment by brandonwillard** [comment]
As I mentioned in [this comment](https://github.com/pymc-devs/symbolic-pymc/issues/6#issuecomment-470765132), there's an interesting avenue to explore regarding cross-`cond`-branch states, and I've included an example via the relation `condpseq`.

Currently, `condpseq` sequentially overwrites the state (i.e. substitutions dictionary) as it goes through the `cond` branches in order, and passes that state along to the branch-specific suggestion functions.

It might be better to provide the separate branch-specific states to the suggestion functions.  For instance, a branch suggestion function could be given a map of branch-labels to variables reified according the the state produced by each branch.  That opens up other considerations, though.

In the aforementioned scenario, how do we provide those branch-refications across branches without evaluating every branch?  Do we sequentially process and use the branch suggestions and return `None` for skipped branch entries in the suggestion function branch-map argument?  

Also, it would be good to understand how cross-branch state suggestions affect relational properties.  Especially since it seems like `condpseq` could be used to implement `conda` and `condu`.

**Comment by brandonwillard** [comment]
Just changed the `condpseq` implementation so that it passes a dict of preceding branch-reified arguments to each suggestion function.  I think this makes more sense than cumulative-state-reified arguments.

**Comment by lucaswiman** [comment]
Could you rebase this branch, and I'll take a look at reviewing it? Apologies for the delays in reviews.

**Comment by brandonwillard** [comment]
No problem.

Also, this one is a WIP, so no rush to get it through.  (If possible, I should probably set it to "draft")

**Comment by brandonwillard** [comment]
FYI: I'm putting together a PR that could substantially change the stream handling (e.g. to operate more along the lines of my Hy implementation, [`hypoKanren`](https://github.com/brandonwillard/hypoKanren/tree/master/hypoKanren)).  The urgency of that effort will depend on whether or not I can find some good workarounds for my current objectives; otherwise, it will likely be my top priority.

**Pull request closed without merging**
